modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"

[[mods]]
modId="farmersmiracle"
version="${version}"
displayName="Farmer's Miracle"
description='''
Collect three sacred orbs from small shrines to slightly boost crop growth around you.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/FarmersMiracle"

[[dependencies.farmersmiracle]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.farmersmiracle]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
