modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"
showAsResourcePack=false

[[mods]]
modId="farmersmiracle"
version="${version}"
displayName="Farmer's Miracle"
description='''
Collect three sacred orbs from small shrines to slightly boost crop growth around you.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/FarmersMiracle"

[[mixins]]
config="farmersmiracle.mixins.json"

[[dependencies.farmersmiracle]]
modId="neoforge"
type="required"
versionRange="[21.11,)"
ordering="NONE"
side="BOTH"

[[dependencies.farmersmiracle]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.21.12)"
ordering="NONE"
side="BOTH"

[[dependencies.farmersmiracle]]
modId="architectury"
type="required"
versionRange="[19,)"
ordering="AFTER"
side="BOTH"
